//! CSPM Export for FDR4 Integration
//!
//! Provides functionality to export CSP processes to CSPM (CSP Machine-readable) format
//! for analysis with FDR4 model checker.

use std::io::Write;

use crate::testing::specs::csp::Process;

/// CSPM (CSP Machine-readable) export
pub struct CspmExporter<'a> {
	process: &'a Process,
}

impl<'a> CspmExporter<'a> {
	pub fn new(process: &'a Process) -> Self {
		Self { process }
	}

	/// Export process to CSPM format for FDR4
	pub fn export<W: Write>(&self, writer: &mut W) -> std::io::Result<()> {
		writeln!(writer, "-- Generated by tightbeam testing framework")?;
		writeln!(writer, "-- Process: {}", self.process.name)?;

		if let Some(desc) = self.process.description {
			writeln!(writer, "-- Description: {desc}")?;
		}

		writeln!(writer)?;

		// Observable alphabet
		self.write_datatype(writer, "Observable", "-- Observable alphabet (Σ)", &self.process.observable)?;

		// Hidden alphabet
		if !self.process.hidden.is_empty() {
			self.write_datatype(writer, "Hidden", "-- Hidden alphabet (τ)", &self.process.hidden)?;
		}

		// States
		self.write_datatype(writer, "States", "-- States", &self.process.states)?;

		// Process definition (simplified LTS representation)
		writeln!(writer, "-- Process: {}", self.process.name)?;
		writeln!(writer, "channel obs : Observable")?;
		writeln!(writer, "channel hid : Hidden")?;
		writeln!(writer)?;

		// Generate process per state
		for state in &self.process.states {
			write!(writer, "{}Process = ", state.0)?;

			if self.process.is_terminal(*state) {
				writeln!(writer, "SKIP")?;
			} else {
				// Get enabled actions
				let enabled = self.process.enabled(*state);

				if enabled.is_empty() {
					writeln!(writer, "STOP")?;
				} else {
					let mut first = true;
					for action in enabled {
						if !first {
							write!(writer, " [] ")?;
						}
						first = false;

						let next_states = self.process.step(*state, &action.event);
						let next = next_states.first().unwrap(); // Take first for simplicity

						if action.is_observable() {
							write!(writer, "obs.{} -> {}Process", action.event.0, next.0)?;
						} else {
							write!(writer, "hid.{} -> {}Process", action.event.0, next.0)?;
						}
					}
					writeln!(writer)?;
				}
			}
			writeln!(writer)?;
		}

		// Main process
		writeln!(
			writer,
			"{} = {}Process \\ {{| hid |}}",
			self.process.name, self.process.initial.0
		)?;

		Ok(())
	}

	/// Helper to write a CSPM datatype definition
	fn write_datatype<W: Write, T: std::fmt::Display>(
		&self,
		writer: &mut W,
		type_name: &str,
		comment: &str,
		items: &std::collections::HashSet<T>,
	) -> std::io::Result<()> {
		writeln!(writer, "{comment}")?;
		writeln!(writer, "datatype {type_name} = ")?;
		let mut iter = items.iter();
		if let Some(first) = iter.next() {
			write!(writer, "  {first}")?;
			for item in iter {
				write!(writer, " | {item}")?;
			}
			writeln!(writer)?;
		}
		writeln!(writer)?;
		Ok(())
	}
}
