#[cfg(not(feature = "std"))]
extern crate alloc;

#[cfg(not(feature = "std"))]
use alloc::boxed::Box;
#[cfg(not(feature = "std"))]
use alloc::sync::Arc;

#[cfg(feature = "std")]
#[allow(unused_imports)] // Used in macro expansion
use std::sync::Arc;

#[cfg(feature = "std")]
use core::fmt;
#[cfg(feature = "std")]
use core::ops;
#[cfg(feature = "std")]
use core::str::FromStr;
#[cfg(all(feature = "std", feature = "tcp"))]
use core::time::Duration;
#[cfg(all(feature = "std", feature = "tcp"))]
use std::io::{Error as IoError, ErrorKind, Read, Write};
#[cfg(feature = "std")]
use std::net::{AddrParseError, SocketAddr};
#[cfg(all(feature = "std", feature = "tcp"))]
use std::net::{TcpListener, TcpStream};

#[cfg(feature = "std")]
use crate::transport::TightBeamAddress;
#[cfg(feature = "tcp")]
use crate::transport::{tcp::sync::TcpTransport, Protocol, ProtocolStream};

#[cfg(any(feature = "tokio", feature = "async-transport"))]
pub mod r#async;
#[cfg(feature = "tcp")]
pub mod sync;

// Canonical definition lives in transport::io so it exists without the TCP features.

/// Abstract TCP listener trait for different networking backends.
#[cfg(feature = "tcp")]
pub trait TcpListenerTrait: Protocol + Send {
	fn accept(&self) -> Result<(Self::Stream, SocketAddr), Self::Error>;
}

/// Socket address abstraction for no_std environments.
#[cfg(not(feature = "std"))]
#[derive(Debug, Clone)]
pub enum SocketAddr {
	V4 { ip: [u8; 4], port: u16 },
	V6 { ip: [u8; 16], port: u16 },
}

#[cfg(all(feature = "std", feature = "tcp"))]
impl Protocol for TcpListener {
	type Listener = TcpListener;
	type Stream = TcpStream;
	type Error = IoError;
	type Transport = TcpTransport<Self::Stream>;
	type Address = TightBeamSocketAddr;

	fn default_bind_address() -> Result<Self::Address, Self::Error> {
		"127.0.0.1:0"
			.parse()
			.map_err(|_| IoError::new(ErrorKind::InvalidInput, "Invalid default address"))
	}

	async fn bind(addr: Self::Address) -> Result<(Self::Listener, Self::Address), Self::Error> {
		let listener = TcpListener::bind(addr.0)?;
		let bound_addr = listener.local_addr()?;
		Ok((listener, TightBeamSocketAddr(bound_addr)))
	}

	async fn connect(addr: Self::Address) -> Result<Self::Stream, Self::Error> {
		TcpStream::connect(addr.0)
	}

	fn create_transport(stream: Self::Stream) -> Self::Transport {
		TcpTransport::from(stream)
	}
}

// The EncryptedProtocol impl for sync TCP lives on the wrapper in sync.rs.

#[cfg(all(feature = "std", feature = "tcp"))]
impl TcpListenerTrait for TcpListener {
	fn accept(&self) -> Result<(Self::Stream, SocketAddr), Self::Error> {
		TcpListener::accept(self)
	}
}

#[cfg(all(feature = "std", feature = "tcp"))]
impl ProtocolStream for TcpStream {
	type Error = IoError;

	fn write_all(&mut self, buf: &[u8]) -> Result<(), Self::Error> {
		Write::write_all(self, buf)
	}

	fn read_exact(&mut self, buf: &mut [u8]) -> Result<(), Self::Error> {
		Read::read_exact(self, buf)
	}

	fn set_timeout(&mut self, timeout: Option<Duration>) -> Result<(), Self::Error> {
		self.set_read_timeout(timeout)?;
		self.set_write_timeout(timeout)?;
		Ok(())
	}
}

/// Newtype wrapper for `SocketAddr` that implements `Into<Vec<u8>>`.
#[cfg(feature = "std")]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TightBeamSocketAddr(pub SocketAddr);

#[cfg(feature = "std")]
impl From<SocketAddr> for TightBeamSocketAddr {
	fn from(addr: SocketAddr) -> Self {
		Self(addr)
	}
}

#[cfg(feature = "std")]
impl From<TightBeamSocketAddr> for SocketAddr {
	fn from(addr: TightBeamSocketAddr) -> Self {
		addr.0
	}
}

#[cfg(feature = "std")]
impl From<TightBeamSocketAddr> for Vec<u8> {
	fn from(addr: TightBeamSocketAddr) -> Self {
		std::format!("{}", addr.0).into_bytes()
	}
}

#[cfg(feature = "std")]
impl fmt::Display for TightBeamSocketAddr {
	fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
		self.0.fmt(f)
	}
}

#[cfg(feature = "std")]
impl FromStr for TightBeamSocketAddr {
	type Err = AddrParseError;

	fn from_str(s: &str) -> Result<Self, Self::Err> {
		Ok(Self(s.parse()?))
	}
}

#[cfg(feature = "std")]
impl ops::Deref for TightBeamSocketAddr {
	type Target = SocketAddr;

	fn deref(&self) -> &Self::Target {
		&self.0
	}
}

#[cfg(feature = "std")]
impl TightBeamAddress for TightBeamSocketAddr {}

/// Macro to generate the common transport implementation for both sync
/// and async.
///
/// Defines the transport struct itself plus the `From<S>` constructor,
/// key-dropping `Drop`, and shared trait impls. The struct definition is
/// the single source for the field list.
#[doc(hidden)]
#[macro_export]
macro_rules! impl_tcp_common {
	($transport:ident, $stream_trait:path) => {
		/// TCP transport over a stream `S`, generated by `impl_tcp_common!`.
		pub struct $transport<
			S: $stream_trait,
			P: $crate::crypto::profiles::CryptoProvider = $crate::crypto::profiles::DefaultCryptoProvider,
		> {
			pub(crate) stream: S,
			#[cfg(feature = "transport-policy")]
			pub(crate) restart_policy: Box<dyn $crate::transport::policy::RestartPolicy>,
			#[cfg(feature = "transport-policy")]
			pub(crate) emitter_gate: $crate::policy::GateChain,
			#[cfg(feature = "transport-policy")]
			pub(crate) collector_gate: $crate::policy::GateChain,
			#[cfg(feature = "x509")]
			pub(crate) encryption: $crate::transport::state::EncryptionConfig<P>,
			#[cfg(feature = "x509")]
			pub(crate) state: $crate::transport::state::SessionState,
			#[cfg(any(feature = "x509", all(feature = "std", feature = "transport-policy")))]
			pub(crate) limits: $crate::transport::TransportLimits,
			#[cfg(feature = "x509")]
			pub(crate) server_handshake: Option<$crate::transport::handshake::BoxedServerHandshake>,
			/// Connection instrumentation collector.
			#[cfg(feature = "instrument")]
			pub(crate) trace: Option<$crate::trace::TraceCollector>,
			pub(crate) _phantom: core::marker::PhantomData<P>,
		}

		impl<S: $stream_trait, P: $crate::crypto::profiles::CryptoProvider> From<S> for $transport<S, P>
		where
			TransportError: From<S::Error>,
		{
			fn from(stream: S) -> Self {
				Self {
					stream,
					#[cfg(feature = "transport-policy")]
					restart_policy: Box::new($crate::transport::policy::NoRestart),
					#[cfg(feature = "transport-policy")]
					emitter_gate: $crate::policy::GateChain::default(),
					#[cfg(feature = "transport-policy")]
					collector_gate: $crate::policy::GateChain::default(),
					#[cfg(feature = "x509")]
					encryption: $crate::transport::state::EncryptionConfig::default(),
					#[cfg(feature = "x509")]
					state: $crate::transport::state::SessionState::default(),
					#[cfg(any(feature = "x509", all(feature = "std", feature = "transport-policy")))]
					limits: $crate::transport::TransportLimits::default(),
					#[cfg(feature = "x509")]
					server_handshake: None,
					#[cfg(feature = "instrument")]
					trace: None,
					_phantom: core::marker::PhantomData,
				}
			}
		}

		#[cfg(feature = "instrument")]
		impl<S: $stream_trait, P: $crate::crypto::profiles::CryptoProvider> $transport<S, P>
		where
			TransportError: From<S::Error>,
		{
			/// Attach the connection's instrumentation collector.
			#[must_use]
			pub fn with_trace(mut self, trace: $crate::trace::TraceCollector) -> Self {
				self.trace = Some(trace);
				self
			}

			/// Share of the connection's instrumentation collector, if
			/// attached.
			pub fn trace(&self) -> Option<$crate::trace::TraceCollector> {
				self.trace.as_ref().map($crate::trace::TraceCollector::share)
			}
		}

		#[cfg(feature = "x509")]
		impl<S: $stream_trait, P: $crate::crypto::profiles::CryptoProvider> $crate::transport::X509ClientConfig for $transport<S, P>
		where
			TransportError: From<S::Error>,
		{
			type CryptoProvider = P;

			fn with_encryption(mut self, encryption: $crate::transport::state::DialableEncryption<P>) -> Self {
				self.encryption = encryption.into_inner();
				self.provision_from_encryption()
			}

			fn with_trust_store(mut self, store: Arc<dyn $crate::crypto::x509::store::CertificateTrust>) -> Self {
				self.encryption.trust_store = Some(store);
				self.provision_from_encryption()
			}

			fn with_client_identity(
				mut self,
				cert: Arc<$crate::x509::Certificate>,
				key: Arc<$crate::transport::handshake::HandshakeKeyManager<P>>,
			) -> Self {
				$crate::transport::state::ClientIdentity::new(cert, key).install(&mut self.encryption);
				self
			}

			fn with_server_certificate_chain(mut self, chain: Arc<[$crate::x509::Certificate]>) -> Self {
				self.encryption.server_certificate_chain = Some(chain);
				self
			}

			fn with_handshake_protocol(mut self, kind: $crate::transport::handshake::HandshakeProtocolKind) -> Self {
				self.encryption.handshake_protocol = kind;
				self
			}

			fn with_receipt_approver(
				mut self,
				approver: Arc<dyn $crate::transport::handshake::receipt::ReceiptApprover>,
			) -> Self {
				self.encryption.receipt_approver = Some(approver);
				self
			}

			#[cfg(feature = "instrument")]
			fn with_trace(mut self, trace: $crate::trace::TraceCollector) -> Self {
				self.trace = Some(trace);
				self
			}
		}

		#[cfg(feature = "x509")]
		impl<S: $stream_trait, P: $crate::crypto::profiles::CryptoProvider> $transport<S, P>
		where
			TransportError: From<S::Error>,
		{
			/// Move to `Provisioned` when this transport's configuration
			/// expects encryption.
			///
			/// Every way of provisioning this transport ends here, so the
			/// phase and the configuration cannot disagree.
			pub(crate) fn provision(&mut self) {
				self.state.provision_for(&self.encryption);
			}

			/// Builder form of [`Self::provision`].
			fn provision_from_encryption(mut self) -> Self {
				self.provision();
				self
			}

			/// Peer certificate after completed mutual authentication.
			/// `None` if unused or incomplete.
			pub fn peer_certificate(&self) -> Option<&$crate::x509::Certificate> {
				match self.state.phase() {
					$crate::transport::state::SessionPhase::Encrypted(session) => session.peer(),
					_ => None,
				}
			}

			/// Negotiated multiplexing settings. `None` means single-flight.
			pub fn negotiated_mux(&self) -> Option<$crate::transport::handshake::negotiation::MuxSettings> {
				match self.state.phase() {
					$crate::transport::state::SessionPhase::Encrypted(session) => session.mux(),
					_ => None,
				}
			}

			/// Dual-signed session receipt from a budget-bearing handshake.
			pub fn session_receipt(&self) -> Option<&$crate::transport::handshake::receipt::StoredReceipt> {
				match self.state.phase() {
					$crate::transport::state::SessionPhase::Encrypted(session) => session.receipt(),
					_ => None,
				}
			}

			/// Override the budget-grant policy consulted between the
			/// client's transport offer and the server's accept. Without
			/// an authorizer the server grants its local configuration
			/// ceiling.
			#[must_use]
			pub fn with_transport_authorizer(
				mut self,
				authorizer: Arc<dyn $crate::transport::handshake::negotiation::TransportAuthorizer>,
			) -> Self {
				self.encryption.transport_authorizer = Some(authorizer);
				self
			}

			/// Session outcome observer for budget-bearing handshakes this endpoint serves.
			#[must_use]
			pub fn with_session_observer(
				mut self,
				observer: Arc<dyn $crate::transport::handshake::receipt::SessionObserver>,
			) -> Self {
				self.encryption.session_observer = Some(observer);
				self
			}

			/// True while this endpoint expects an encryption handshake that has
			/// not completed yet. Such reads face an unauthenticated peer, so the
			/// read layer applies the tight `handshake_wire` ceiling and the
			/// handshake deadline instead of the general envelope limits.
			pub(crate) fn is_handshake_pending(&self) -> bool {
				self.state.phase().is_handshake_pending()
			}
		}

		#[cfg(feature = "transport-policy")]
		impl<S: $stream_trait, P: $crate::crypto::profiles::CryptoProvider> $crate::transport::policy::RestartConfig for $transport<S, P>
		where
			TransportError: From<S::Error>,
		{
			fn with_restart<Pol: RestartPolicy + 'static>(mut self, policy: Pol) -> Self {
				self.restart_policy = Box::new(policy);
				self
			}
		}

		#[cfg(feature = "transport-policy")]
		impl<S: $stream_trait, P: $crate::crypto::profiles::CryptoProvider> $crate::transport::policy::EmitterGateConfig for $transport<S, P>
		where
			TransportError: From<S::Error>,
		{
			fn with_emitter_gate<G: GatePolicy + 'static>(mut self, gate: G) -> Self {
				self.emitter_gate.push(gate);
				self
			}
		}

		#[cfg(feature = "transport-policy")]
		impl<S: $stream_trait, P: $crate::crypto::profiles::CryptoProvider> $crate::transport::policy::CollectorGateConfig for $transport<S, P>
		where
			TransportError: From<S::Error>,
		{
			fn with_collector_gate<G: GatePolicy + 'static>(mut self, gate: G) -> Self {
				self.collector_gate.push(gate);
				self
			}
		}

		#[cfg(feature = "transport-policy")]
		impl<S: $stream_trait, P: $crate::crypto::profiles::CryptoProvider> $crate::transport::policy::TimeoutConfig for $transport<S, P>
		where
			TransportError: From<S::Error>,
		{
			fn with_timeout(mut self, timeout: core::time::Duration) -> Self {
				self.limits.operation_timeout = timeout;
				self
			}
		}

		#[cfg(all(feature = "transport-policy", not(feature = "x509")))]
		impl<S: $stream_trait, P: $crate::crypto::profiles::CryptoProvider> $crate::transport::MessageEmitter for $transport<S, P>
		where
			TransportError: From<S::Error>,
		{
			type EmitterGate = dyn GatePolicy;
			type RestartPolicy = dyn RestartPolicy;

			fn to_restart_policy_ref(&self) -> &Self::RestartPolicy {
				self.restart_policy.as_ref()
			}

			fn to_emitter_gate_policy_ref(&self) -> &Self::EmitterGate {
				&self.emitter_gate
			}
		}

		// Without x509 there is no encryption-aware override, so the
		// default single-flight collector applies. The gate items only
		// exist under transport-policy.
		#[cfg(not(all(feature = "x509", feature = "transport-policy")))]
		impl<S: $stream_trait> $crate::transport::MessageCollector for $transport<S>
		where
			TransportError: From<S::Error>,
		{
			#[cfg(feature = "transport-policy")]
			type CollectorGate = dyn GatePolicy;

			#[cfg(feature = "transport-policy")]
			fn collector_gate(&self) -> &Self::CollectorGate {
				&self.collector_gate
			}
		}

		// Audit source for gate verdicts. One definition feeds every
		// collector plane this transport serves.
		#[cfg(feature = "transport-policy")]
		impl<S: $stream_trait, P: $crate::crypto::profiles::CryptoProvider> $crate::transport::GateAudit for $transport<S, P>
		where
			TransportError: From<S::Error>,
		{
			#[cfg(feature = "instrument")]
			fn audit_trace(&self) -> Option<&$crate::trace::TraceCollector> {
				self.trace.as_ref()
			}
		}

		#[cfg(not(feature = "transport-policy"))]
		impl<S: $stream_trait> $crate::transport::MessageEmitter for $transport<S>
		where
			TransportError: From<S::Error>
		{}

		// State accessors shared as-is by the sync and async transports.
		// A single definition keeps the two from drifting.
		#[cfg(feature = "x509")]
		impl<S: $stream_trait, P: $crate::crypto::profiles::CryptoProvider>
			$crate::transport::state::SealedProtocolState for $transport<S, P>
		{
		}

		#[cfg(all(feature = "x509", any(feature = "transport-cms", feature = "transport-ecies")))]
		impl<S: $stream_trait, P: $crate::crypto::profiles::CryptoProvider>
			$crate::transport::state::ServerHandshakeSlot for $transport<S, P>
		where
			TransportError: From<S::Error>,
		{
			fn server_handshake_mut(&mut self) -> &mut Option<BoxedServerHandshake> {
				&mut self.server_handshake
			}
		}

		#[cfg(feature = "x509")]
		impl<S: $stream_trait, P: $crate::crypto::profiles::CryptoProvider + Send + Sync + 'static>
			$crate::transport::state::EncryptedProtocolState for $transport<S, P>
		where
			TransportError: From<S::Error>,
		{
			type CryptoProvider = P;

			fn session_state(&self) -> &$crate::transport::state::SessionState {
				&self.state
			}

			fn session_state_mut(&mut self) -> &mut $crate::transport::state::SessionState {
				&mut self.state
			}

			fn encryption(&self) -> &$crate::transport::state::EncryptionConfig<P> {
				&self.encryption
			}

			fn limits(&self) -> &$crate::transport::TransportLimits {
				&self.limits
			}

			#[cfg(feature = "instrument")]
			fn to_trace_ref(&self) -> Option<&TraceCollector> {
				self.trace.as_ref()
			}

			fn to_handshake_timeout(&self) -> Duration {
				self.limits.handshake_timeout
			}
		}
	};
}
